
<script type="text/javascript" src="<?=$this->baseUrl('assets/js/jquery.js')?>"></script>
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.3/jquery-ui.js"></script>
<script type="text/javascript" src="<?=$this->baseUrl('assets/libraries/isotope/jquery.isotope.min.js')?>"></script>

<script type="text/javascript" src="<?=$this->baseUrl('assets/libraries/bootstrap-sass/vendor/assets/javascripts/bootstrap/transition.js')?>"></script>
<script type="text/javascript" src="<?=$this->baseUrl('assets/libraries/bootstrap-sass/vendor/assets/javascripts/bootstrap/collapse.js')?>"></script>
<script type="text/javascript" src="<?=$this->baseUrl('assets/libraries/jquery-bxslider/jquery.bxslider.min.js')?>"></script>
<script type="text/javascript" src="<?=$this->baseUrl('assets/libraries/flexslider/jquery.flexslider.js')?>"></script>
<script type="text/javascript" src="<?=$this->baseUrl('assets/js/jquery.chained.min.js')?>"></script>
<script type="text/javascript" src="<?=$this->baseUrl('assets/js/realocation.js')?>"></script>
